# Generated by Django 4.2.10 on 2024-02-23 15:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tag_alter_page_image_alter_page_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
